### ISSUE TITLE
Protocol for Passing Arguments to the "data" field of the Drone's Infer function.

### ISSUE THREAD

**Issue by FraserP117** [ReactiveBayes/RxInferExamples.jl#2]
I am presently attempting to write a "simplified" version of the existing [Mountain Car example](https://reactivebayes.github.io/RxInfer.jl/stable/examples/advanced_examples/Active%20Inference%20Mountain%20car/#examples-active-inference-mountain-car) - for eventual instantiation as an [RxEnvironments](https://github.com/biaslab/RxEnvironments.jl) simulation. To that end, I am shamelessly stealing some of the Drone example's code. 

My question is about the drone's ```infer``` wrapper: ```move_to_target```, which I have reproduced below:

```julia
function move_to_target(drone::Drone, env::Environment, start::State, target, horizon, dt)

    results = infer(
        model = drone_model(
            drone = drone, 
            environment = env,
            horizon = horizon,
            dt = dt
        ),
        data  = (
            initial_state = collect(get_state(start)), 
            goal = [target[1], target[2], 0, 0, 0, 0],
        ),
        meta  = drone_meta(),
        returnvars = (s = KeepLast(), u = KeepLast())
    )

    return results

end
```

It is my understanding that fields belonging to the ```@drone_model``` should be passed to ```infer``` via ```infer```'s ```data``` field. Indeed that is done here, however some of the ```@drone_model```'s fields are passed **directly** into the call to ```drone_model``` while the others are passed to the ```data``` field. 

I can't account for why this should be the case. Should we always pass all model arguments to ```infer```'s ```data``` field? clearly it is not a "necessity", since the drone example works as intended. In that case, what is the protocol for partitioning the model's arguments between its constructor as opposed to ```infer```'s ```data``` field?

Any thoughts are appreciated!

**Comment by albertpod** [comment]
Thoughts @wouterwln?

**Comment by wouterwln** [comment]
In `RxInfer`, there is a difference between data and parameters. For data, we create a delta factor node in the factor graph and make sure we can attach factor nodes to this data. For parameters, this isn't necessarily the case. Consider the following (wacky) model:
```julia
@model function recursive_model(n, y)
    if n == 1
        x ~ NormalMeanVariance(0, 1)
    else
        x ~ recursive_model(n = n-1)
    end
    y ~ NormalMeanVariance(x, 1)
end
```

Now in this model, we have an interface `n` that we don't actually want to create a factor node for (the same as the `env` or `horizon` parameters in your `drone_model`. However, for `y`, which is actually data, we want to pass it as data. So inference in this model would be done by calling:
```julia
infer(model=recursive_model(n=10), data = (y = 1,))
```
I think that's the difference you're after, right?

**Comment by FraserP117** [comment]
Aha, thanks @wouterwln.

So it seems that the data field is used to pass all arguments for which we want to create factor nodes - or perhaps just any node in the factor graph. Direct invocations of model parameters in the model function simply act to specify more abstract "meta-information" about the model's structure: the recursion depth in your above example. Have I understood that correctly?

A basic schema would then be: _"data = graph nodes of some kind"_ and: _"parameters = some graph metadata"_.

Indeed, that was the distinction I was after, thanks again.

**Comment by wouterwln** [comment]
Sure, but note that you can also pass stuff you want to make factor nodes of in the parameters.
```julia
@model function something(a, b, y)
    x ~ Normal(mean = a, variance = b)
    y ~ Normal(mean = x, variance = 1)
end
```
can also be invoked with:
```julia
infer(model = something(a = 1, b = 1), data = (y = 0.0,))
```
The only thing is that you cannot pass parameters as data. Strictly speaking, `a` and `b` serve as "parameters" in a sense that they parameterize a prior distribution, but there is no functional difference between passing `a` and `b` as data in this setting.

**Comment by FraserP117** [comment]
Ahh ok. That does clear up my query. Thanks @wouterwln.
